#==================================================
# https://github.com/P3TERX/openwrt-build-env
# Description: OpenWrt build environment in docker
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com (chinese)
#==================================================
name: Docker images publish

on:
  repository_dispatch:
    types: [Manual*, Auto* ,test]
  push:
    paths:
      - 'Dockerfile'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and push
      uses: docker/build-push-action@v1
      with:
        push: true
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: p3terx/openwrt-build-env
        tags: latest,18.04
        build_args: IMAGE_TAG=18.04
        dockerfile: Dockerfile
        path: .

  tigger:
    runs-on: ubuntu-latest
    needs: publish

    steps:
    - name: Trigger other image builds
      if: (!contains(github.event.action, 'test'))
      env:
        ACTIONS_TRIGGER_TOKEN: ${{ secrets.ACTIONS_TRIGGER }}
        REPO_NAME: P3TERX/Gitpod-OpenWrt
        TRIGGER_KEYWORDS: 'Auto trigger'
      run: |
        sh <(curl -fsSL git.io/trigger.sh) "$ACTIONS_TRIGGER_TOKEN" "$REPO_NAME" "$TRIGGER_KEYWORDS"
